name: 'Fake-News-Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:
  
defaults:
  run:
    working-directory: ./tf/models/network
    
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v3
          
      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          
      - uses: hashicorp/setup-terraform@v2

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: cd ./tf/models/network && terraform init
        continue-on-error: true

      - name: Terraform Validate
        id: validate
        run: cd ./tf/models/network && terraform validate
      
      - name: Terraform Plan
        id: plan
        run: cd ./tf/models/network && terraform plan -var-file=../../applications/env/develop.tfvars -lock=false
        continue-on-error: true
      
      - name: Terraform Apply
        id: apply
        run: cd ./tf/models/network && terraform apply -auto-approve -input=false -var-file=../../applications/env/develop.tfvars -lock=false
        continue-on-error: true
      
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
    
    
    
